# Generated by Django 3.1.2 on 2020-10-01 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=280)),
                ('boast_roast', models.CharField(choices=[('B', 'Boast'), ('R', 'Roast')], default='B', max_length=1)),
                ('up_field', models.IntegerField(default=0)),
                ('down_field', models.IntegerField(default=0)),
                ('votes', models.IntegerField(blank=True, default=0, editable=False, null=True)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
